print("Welcome to the Brand Name Generator!")
city = input("What's the name of the city you grew up in?\n")
pet = input("What's your pet's name?\n")
print(f'Your Brand name could be {city} {pet}')
print("Your Brand name could be " + city+" "+pet)
